services:
  - type: web
    name: boutique-store
    env: python
    region: frankfurt
    branch: main

    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn monsite.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.10"
      - - key: DATABASE_URL
          value: "postgresql://boutique_user:XVdPV95VO2JAoc5nHAhLzZyN9k0TM0rQ@dpg-d4crunk9c44c7390nk1g-a.frankfurt-postgres.render.com/boutique_db_jlmp"
