services:
  - type: web
    name: boutique-store
    env: python
    region: frankfurt
    branch: main

    buildCommand: "./build.sh"
    startCommand: "gunicorn monsite.wsgi:application --bind 0.0.0.0:$PORT"

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: PYTHON_VERSION
        value: "3.10"

      - key: DATABASE_URL
        fromDatabase:
          name: boutique-db    # ⚠️ mets ici le nom EXACT de ta base Render
          property: connectionString
